apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: expense-tracker
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:7
      ports:
        - containerPort: 6379
