# Generated by Django 6.0.1 on 2026-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_aiinsight_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
