# Generated by Django 6.0.1 on 2026-01-18 12:26

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")

    default_categories = [
        "food",
        "travel",
        "shopping",
        "healthcare",
        "entertainment",
        "bills",
        "miscellaneous",
    ]

    for name in default_categories:
        Category.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_description'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
